//	Header generated by Constructor for Palm OS¨ 1.5
//
//	Generated at 14:11:04  on Sonntag, 27. Mai 2001
//
//	Generated for file: C:\Dokumente und Einstellungen\Administrator\Eigene Dateien\FFImportExport\Rsc\Starter.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OS¨;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name: 		"FFImport"
//
//	Palm App Version: 		"1.0"



//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainImportButton                          1003	//(Left Origin = 11, Top Origin = 131, Width = 138, Height = 18, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define MainSNField                               1001	//(Left Origin = 30, Top Origin = 40, Width = 100, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 20, Font = Bold, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainStatusField                           1004	//(Left Origin = 60, Top Origin = 0, Width = 90, Height = 12, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainLabelLabel                            1002	//(Left Origin = 40, Top Origin = 20, Usable = 1, Font = Bold 12)


//	Resource: tFRM 1100
#define AboutForm                                 1100	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AboutOKButton                             1105	//(Left Origin = 58, Top Origin = 133, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AboutTitleLabel                           1102	//(Left Origin = 61, Top Origin = 23, Usable = 1, Font = Large)
#define AboutText1Label                           1103	//(Left Origin = 23, Top Origin = 54, Usable = 1, Font = Standard)
#define AboutText2Label                           1104	//(Left Origin = 50, Top Origin = 104, Usable = 1, Font = Bold)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1100
#define OkAlert                                   1100
#define OkAdd                                     0

//	Resource: Talt 1200
#define ErrorAlert                                1200
#define ErrorClose                                0

//	Resource: Talt 1300
#define PortAlert                                 1300
#define PortStop                                  0

//	Resource: Talt 1400
#define SpaceAlert                                1400
#define SpaceClose                                0

//	Resource: Talt 1500
#define EraseAlert                                1500
#define EraseYes                                  0
#define EraseNo                                   1

//	Resource: Talt 1600
#define AppendErrorAlert                          1600
#define AppendErrorClose                          0

//	Resource: Talt 1700
#define ExportAlert                               1700
#define ExportExportdatabase                      0
#define ExportAbort                               1

//	Resource: Talt 1800
#define PCErr1Alert                               1800
#define PCErr1Close                               0

//	Resource: Talt 1900
#define DatabaseEmptyAlert                        1900
#define DatabaseEmptyClose                        0

//	Resource: MBAR 1000
#define MainFormMenuBar                           1000

//	Resource: MENU 1000
#define MainOptionsMenu                           1000
#define MainOptionsExporttoPC                     1000
#define MainOptionsAboutStarterApp                1001

//	Resource: MENU 1100
#define ComSpeedMenu                              1100
#define ComSpeed1200                              1100
#define ComSpeed2400                              1101
#define ComSpeed4800                              1102
#define ComSpeed9600                              1103
#define ComSpeed19200                             1104
#define ComSpeed33600                             1105

//	Resource: PICT 1000
#define BitmapID1000Bitmap                        1000
//	Resource: taif 1000
#define ApplicationIcon1000AppIconFamily          1000
